### ISSUE TITLE
previous triplets exit 

### ISSUE THREAD

**Issue by gari-marcos** [MikulasZelinka/textworld_kg_dataset#1]
Hello, I was looking the dataset and I found there is a special case regarding triplets when it comes to ```exit```. In this case, the triplet is formed by four elements. I would like to know how these triplets are built as they have where does that exit lead without any previous action.
Thank you in advance.

**Comment by xingdi-eric-yuan** [comment]
Hi @gari-marcos , thanks for the question. 
In such case, for example a triplet:
`["exit", "kitchen", "backyard", "south_of"]`
the 3rd element is the room which the kitchen is connected via that exit. It is hidden from the agent/model sometimes since it never knows what room a door is leading to before it actually goes through that door. We keep that room name there to help humans to understand/debug. 

That said, the triplets can be filtered by
```python
def process_exits_in_triplet(triplet):
    # ["exit", "kitchen", "backyard", "south_of"]
    if triplet[0] == "exit":
        return [triplet[0], triplet[1], triplet[3]]
    else:
        return triplet
```
Thanks for reporting and we will make this clearer.

**Comment by xingdi-eric-yuan** [comment]
@gari-marcos , please refer to [GATA](https://github.com/xingdi-eric-yuan/GATA-public). We have released all data and code. Essentially the method/data described in this repo is one component of the GATA project.

**Comment by gari-marcos** [comment]
Thank you! I will check the GATA project.
